/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Trx;

import Config.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Illuminate
 */
public class Pinjam extends javax.swing.JFrame {
    protected DefaultTableModel tbl;
    protected int total_harga;
    protected int stock = 0;
    static int currentTrxID;
    /**
     * Creates new form Pinjam
     */
    public Pinjam() {
        initComponents();
        this._datatables();
    }
    
    private void _datatables() {
        tbl = new DefaultTableModel();
        tbl.addColumn("Nomor Buku");
        tbl.addColumn("Nama Buku");
        tbl.addColumn("Harga Buku");
        cart_table.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZeroLayout = new javax.swing.JPanel();
        btn_back = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Topbar = new javax.swing.JPanel();
        tanggal_hari_ini = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama_anggota = new javax.swing.JTextField();
        text_anggota = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSearch_anggota = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomor_buku = new javax.swing.JTextField();
        btnSearch_book = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        nama_buku = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        due_date = new javax.swing.JComboBox<>();
        btnBook_reset = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btn_resetAll = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnBook_delete = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnBook_submit = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        trx_submit = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cart_table = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        harga_buku = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ZeroLayout.setBackground(new java.awt.Color(255, 255, 255));
        ZeroLayout.setMaximumSize(new java.awt.Dimension(1920, 1080));
        ZeroLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setBackground(new java.awt.Color(22, 30, 84));
        btn_back.setMinimumSize(new java.awt.Dimension(0, 720));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        btn_back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout_x1.png"))); // NOI18N
        btn_back.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 66, 66));

        ZeroLayout.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 66, 66));

        Topbar.setBackground(new java.awt.Color(20, 39, 155));
        Topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanggal_hari_ini.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggal_hari_ini.setForeground(new java.awt.Color(255, 255, 255));
        tanggal_hari_ini.setText("24 Desember 2077");
        Topbar.add(tanggal_hari_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 26, -1, -1));

        ZeroLayout.add(Topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1240, 66));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nama Anggota");
        ZeroLayout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 30));

        nama_anggota.setEnabled(false);
        ZeroLayout.add(nama_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 245, 29));
        ZeroLayout.add(text_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 181, 29));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("ID Anggota");
        ZeroLayout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 30));

        btnSearch_anggota.setBackground(new java.awt.Color(22, 30, 84));
        btnSearch_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch_anggotaMouseClicked(evt);
            }
        });
        btnSearch_anggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cari");
        btnSearch_anggota.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        ZeroLayout.add(btnSearch_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 60, 29));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nomor Buku");
        ZeroLayout.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, 30));
        ZeroLayout.add(nomor_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 181, 29));

        btnSearch_book.setBackground(new java.awt.Color(22, 30, 84));
        btnSearch_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch_bookMouseClicked(evt);
            }
        });
        btnSearch_book.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cari");
        btnSearch_book.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        ZeroLayout.add(btnSearch_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 70, 29));

        nama_buku.setEnabled(false);
        ZeroLayout.add(nama_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 260, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Nama Buku");
        ZeroLayout.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Lama peminjaman (hari)");
        ZeroLayout.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 180, 30));

        due_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "7", "14", "30" }));
        due_date.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                due_dateItemStateChanged(evt);
            }
        });
        ZeroLayout.add(due_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 260, 30));

        btnBook_reset.setBackground(new java.awt.Color(22, 30, 84));
        btnBook_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_resetMouseClicked(evt);
            }
        });
        btnBook_reset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Reset");
        btnBook_reset.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        ZeroLayout.add(btnBook_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 70, 30));

        btn_resetAll.setBackground(new java.awt.Color(22, 30, 84));
        btn_resetAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetAllMouseClicked(evt);
            }
        });
        btn_resetAll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Reset");
        btn_resetAll.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        ZeroLayout.add(btn_resetAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 70, 30));

        btnBook_delete.setBackground(new java.awt.Color(255, 92, 88));
        btnBook_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_deleteMouseClicked(evt);
            }
        });
        btnBook_delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(255, 92, 88));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Hapus");
        btnBook_delete.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        ZeroLayout.add(btnBook_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 80, 30));

        btnBook_submit.setBackground(new java.awt.Color(87, 204, 153));
        btnBook_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_submitMouseClicked(evt);
            }
        });
        btnBook_submit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tambah");
        btnBook_submit.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        ZeroLayout.add(btnBook_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 70, 30));

        trx_submit.setBackground(new java.awt.Color(87, 204, 153));
        trx_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trx_submitMouseClicked(evt);
            }
        });
        trx_submit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Simpan");
        trx_submit.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        ZeroLayout.add(trx_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, 70, 30));

        cart_table = new javax.swing.JTable() {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        cart_table.setAutoCreateRowSorter(true);
        cart_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cart_table.setRowHeight(25);
        cart_table.setRowSelectionAllowed(false);
        cart_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(cart_table);

        ZeroLayout.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 600, 280));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Harga Buku");
        ZeroLayout.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 90, 30));

        harga_buku.setEnabled(false);
        ZeroLayout.add(harga_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 260, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Total");
        ZeroLayout.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 90, 30));

        txt_total.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txt_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total.setText("0");
        txt_total.setEnabled(false);
        ZeroLayout.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 260, 72));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ZeroLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ZeroLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch_anggotaMouseClicked
        try {
            String query = "SELECT * FROM anggota WHERE id_anggota = '" + text_anggota.getText() + "'";
            Connection conn = (Connection)Database.GetConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            if(result.next()) {
                nama_anggota.setText(result.getString("nama"));
            } else {
                nama_anggota.setText("");
                JOptionPane.showMessageDialog(rootPane, "Maaf, anggota tidak ditemukan silahkan periksa kembali!");
            }
            ps.close();
            conn.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSearch_anggotaMouseClicked

    private void btnSearch_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch_bookMouseClicked
        try {
            String query = "SELECT * FROM buku JOIN pengarang ON buku.id_pengarang = pengarang.id_pengarang WHERE id_buku = '" + nomor_buku.getText() + "'";
            Connection conn = (Connection)Database.GetConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            if(result.next()) {
                this.stock = Integer.valueOf(result.getString("stock"));
                nama_buku.setText(result.getString("buku.nama") + " - " + result.getString("pengarang.nama"));
                harga_buku.setText(result.getString("buku.harga"));
            } else {
                this.stock = 0;
                nama_buku.setText("");
                JOptionPane.showMessageDialog(rootPane, "Maaf, buku tidak ditemukan silahkan periksa kembali!");
            }
            ps.close();
            conn.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSearch_bookMouseClicked

    private void due_dateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_due_dateItemStateChanged
        this._setTotal();
    }//GEN-LAST:event_due_dateItemStateChanged

    private void btnBook_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_resetMouseClicked
        this.resetBook();
    }//GEN-LAST:event_btnBook_resetMouseClicked

    private void btn_resetAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetAllMouseClicked
        this.resetAll();
    }//GEN-LAST:event_btn_resetAllMouseClicked

    private void btnBook_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_deleteMouseClicked
        if(cart_table.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data yang akan dihapus terlebih dahulu!");
        } else {
            int row = cart_table.getSelectedRow();
            tbl.removeRow(row);
            _setTotal();
        }
    }//GEN-LAST:event_btnBook_deleteMouseClicked

    private void btnBook_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_submitMouseClicked
        if(!nomor_buku.getText().equals("") && !nama_buku.getText().equals("") && !harga_buku.getText().equals("")) {
            if(this.stock != 0) {
                tbl.addRow(new Object[] {
                    nomor_buku.getText(),
                    nama_buku.getText(),
                    harga_buku.getText()
                });
                this._setTotal();
                this.resetBook();
            } else {
                JOptionPane.showMessageDialog(this, "Stok buku ini sedang kosong!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
        }
    }//GEN-LAST:event_btnBook_submitMouseClicked

    private void trx_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trx_submitMouseClicked
        Vector dataTable = tbl.getDataVector();
        if(!text_anggota.getText().equals("") && !nama_anggota.getText().equals("") && dataTable.toArray().length != 0 && this.total_harga != 0) {
            String id_petugas = String.valueOf(Model.User.getId());
            String id_anggota = text_anggota.getText();
            String query;
            PreparedStatement ps;
            try {
                query = "INSERT INTO transaksi (id_transaksi, id_petugas, id_anggota, status, harga_total, tanggal_dibuat, tanggal_kembali, tanggal_dikembalikan) VALUES (NULL, '" + id_petugas + "', '" + id_anggota + "', 'Dipinjam', '" + this.total_harga + "', CURRENT_DATE(), DATE_ADD(CURRENT_DATE(), INTERVAL " + due_date.getSelectedItem() + " DAY), NULL)";
                Connection conn = (Connection)Database.GetConnection();
                try {
                    conn.setAutoCommit(false);
                    ps = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
                    ps.executeUpdate();
                    ResultSet res = ps.getGeneratedKeys();
                    if(res.next()) {
                        this.currentTrxID = res.getInt(1);
                        Vector data = tbl.getDataVector();
                        for(int i = 0; i < data.toArray().length; i++) {
                            String id_buku = tbl.getValueAt(i, 0).toString();
                            query = "INSERT INTO detail_transaksi (id_transaksi, id_buku) VALUES ('" + this.currentTrxID + "', '" + id_buku + "')";
                            ps = conn.prepareStatement(query);
                            ps.execute();
                            
                            query = "UPDATE buku SET stock = IF(stock > 0, stock - 1, 0) WHERE id_buku = " + id_buku;
                            ps = conn.prepareStatement(query);
                            ps.execute();
                        }
                    }
                    conn.commit();
                    this.resetAll();
                    JOptionPane.showMessageDialog(this, "Berhasil menambahkan data");
                } catch(Exception ex) {
                    conn.rollback();
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menambahkan data");
                } finally {
                    conn.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan dengan database");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
        }
    }//GEN-LAST:event_trx_submitMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        new Main.Transaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    protected  void _setTotal() {
        Vector data = tbl.getDataVector();
        int harga = 0;
        int lama_hari = Integer.valueOf(due_date.getSelectedItem().toString());
        for(int i = 0; i < data.toArray().length; i++) {
            int harga_per_buku = Integer.parseInt(cart_table.getValueAt(i, 2).toString());
            harga = harga + (harga_per_buku * lama_hari);
        }
        this.total_harga = harga;
        txt_total.setText(String.valueOf(this.total_harga));
    }
    
    protected  void resetBook() {
        nomor_buku.setText("");
        nama_buku.setText("");
        harga_buku.setText("");
    }
    
    protected  void resetAll() {
        this.resetBook();
        this.resetAnggota();
        this.total_harga = 0;
        txt_total.setText(String.valueOf(this.total_harga));
        tbl.setRowCount(0);
    }
    
    protected  void resetAnggota() {
        text_anggota.setText("");
        nama_anggota.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Topbar;
    private javax.swing.JPanel ZeroLayout;
    private javax.swing.JPanel btnBook_delete;
    private javax.swing.JPanel btnBook_reset;
    private javax.swing.JPanel btnBook_submit;
    private javax.swing.JPanel btnSearch_anggota;
    private javax.swing.JPanel btnSearch_book;
    private javax.swing.JPanel btn_back;
    private javax.swing.JPanel btn_resetAll;
    private javax.swing.JTable cart_table;
    private javax.swing.JComboBox<String> due_date;
    private javax.swing.JTextField harga_buku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nama_anggota;
    private javax.swing.JTextField nama_buku;
    private javax.swing.JTextField nomor_buku;
    private javax.swing.JLabel tanggal_hari_ini;
    private javax.swing.JTextField text_anggota;
    private javax.swing.JPanel trx_submit;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
