/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.MasterData;

import Config.Database;
import Main.Date.CurrentDate;
import Main.Master;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Illuminate
 */
public class Buku extends javax.swing.JFrame {
    protected String selectedBukuID;
    /**
     * Creates new form Buku
     */
    public Buku() {
        initComponents();
        _datatables();
    }
    
    private void _setDate() {
        CurrentDate cd = new CurrentDate();
        tanggal_hari_ini.setText(cd.getCurDate());
    }
    
    private void _datatables() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Nama");
        tbl.addColumn("ID Pengarang");
        tbl.addColumn("Pengarang");
        tbl.addColumn("ID Penerbit");
        tbl.addColumn("Penerbit");
        tbl.addColumn("Harga");
        tbl.addColumn("Jumlah Hal");
        tbl.addColumn("Stock");
        buku_table.setModel(tbl);
        try {
            String query = "SELECT * FROM buku JOIN penerbit ON buku.id_penerbit = penerbit.id_penerbit JOIN pengarang ON buku.id_pengarang = pengarang.id_pengarang ORDER BY id_buku DESC";
            Connection conn = (Connection)Database.GetConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            while(result.next()) {
                tbl.addRow(new Object[] {
                    result.getString("id_buku"),
                    result.getString("buku.nama"),
                    result.getString("pengarang.id_pengarang"),
                    result.getString("pengarang.nama"),
                    result.getString("penerbit.id_penerbit"),
                    result.getString("penerbit.nama"),
                    result.getString("buku.harga"),
                    result.getString("buku.jumlah_halaman"),
                    result.getString("buku.stock"),
                });
                buku_table.setModel(tbl);
            }
            ps.close();
            conn.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Terjadi kesalahan saat mengambil data");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZeroLayout5 = new javax.swing.JPanel();
        btn_back5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Topbar = new javax.swing.JPanel();
        tanggal_hari_ini = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        buku_table = new javax.swing.JTable();
        btnBook_reset = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnBook_delete = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnBook_submit = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnBook_save = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        nama_pengarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_pengarang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSearch_pengarang = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nama_penerbit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_penerbit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnSearch_penerbit = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_hal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Master - Buku");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        ZeroLayout5.setBackground(new java.awt.Color(255, 255, 255));
        ZeroLayout5.setMaximumSize(new java.awt.Dimension(1920, 1080));
        ZeroLayout5.setPreferredSize(new java.awt.Dimension(1280, 720));
        ZeroLayout5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back5.setBackground(new java.awt.Color(22, 30, 84));
        btn_back5.setMinimumSize(new java.awt.Dimension(0, 720));
        btn_back5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_back5MouseClicked(evt);
            }
        });
        btn_back5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout_x1.png"))); // NOI18N
        btn_back5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 66, 66));

        ZeroLayout5.add(btn_back5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 66, 66));

        Topbar.setBackground(new java.awt.Color(20, 39, 155));
        Topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanggal_hari_ini.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggal_hari_ini.setForeground(new java.awt.Color(255, 255, 255));
        tanggal_hari_ini.setText("24 Desember 2077");
        Topbar.add(tanggal_hari_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 26, -1, -1));

        ZeroLayout5.add(Topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1240, 66));
        ZeroLayout5.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 300, 29));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Nama");
        ZeroLayout5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        buku_table = new javax.swing.JTable() {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        buku_table.setAutoCreateRowSorter(true);
        buku_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        buku_table.setRowHeight(25);
        buku_table.getTableHeader().setReorderingAllowed(false);
        buku_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buku_tableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(buku_table);

        ZeroLayout5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 830, -1));

        btnBook_reset.setBackground(new java.awt.Color(22, 30, 84));
        btnBook_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_resetMouseClicked(evt);
            }
        });
        btnBook_reset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Reset");
        btnBook_reset.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 65, 30));

        ZeroLayout5.add(btnBook_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 65, 30));

        btnBook_delete.setBackground(new java.awt.Color(255, 92, 88));
        btnBook_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_deleteMouseClicked(evt);
            }
        });
        btnBook_delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(255, 92, 88));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Hapus");
        btnBook_delete.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 65, 30));

        ZeroLayout5.add(btnBook_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 65, 30));

        btnBook_submit.setBackground(new java.awt.Color(87, 204, 153));
        btnBook_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_submitMouseClicked(evt);
            }
        });
        btnBook_submit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(87, 204, 153));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tambah");
        btnBook_submit.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 65, 30));

        ZeroLayout5.add(btnBook_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 65, 30));

        btnBook_save.setBackground(new java.awt.Color(250, 173, 128));
        btnBook_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_saveMouseClicked(evt);
            }
        });
        btnBook_save.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(250, 173, 128));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Ubah");
        btnBook_save.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 65, 30));

        ZeroLayout5.add(btnBook_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 65, 30));

        txt_cari.setForeground(new java.awt.Color(153, 153, 153));
        txt_cari.setText("Cari berdasarkan nama");
        txt_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariFocusLost(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        ZeroLayout5.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 260, 29));

        nama_pengarang.setEnabled(false);
        ZeroLayout5.add(nama_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 245, 29));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nama Pengarang");
        ZeroLayout5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));
        ZeroLayout5.add(txt_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 181, 29));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("ID Pengarang");
        ZeroLayout5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        btnSearch_pengarang.setBackground(new java.awt.Color(22, 30, 84));
        btnSearch_pengarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch_pengarangMouseClicked(evt);
            }
        });
        btnSearch_pengarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cari");
        btnSearch_pengarang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        ZeroLayout5.add(btnSearch_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, 29));

        nama_penerbit.setEnabled(false);
        ZeroLayout5.add(nama_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 245, 29));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nama Penerbit");
        ZeroLayout5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 30));
        ZeroLayout5.add(txt_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 181, 29));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("ID Penerbit");
        ZeroLayout5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 30));

        btnSearch_penerbit.setBackground(new java.awt.Color(22, 30, 84));
        btnSearch_penerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch_penerbitMouseClicked(evt);
            }
        });
        btnSearch_penerbit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cari");
        btnSearch_penerbit.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        ZeroLayout5.add(btnSearch_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 60, 29));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Harga per hari");
        ZeroLayout5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 30));
        ZeroLayout5.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 300, 29));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Stock");
        ZeroLayout5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, 30));
        ZeroLayout5.add(txt_hal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 160, 29));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Jumlah Halaman");
        ZeroLayout5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, 30));
        ZeroLayout5.add(txt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 110, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ZeroLayout5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ZeroLayout5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_back5MouseClicked
        new Master().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_back5MouseClicked

    private void buku_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_tableMouseClicked
        int row = buku_table.getSelectedRow();
        String id = buku_table.getValueAt(row, 0).toString();
        String nama = buku_table.getValueAt(row, 1).toString();
        String id_peng = buku_table.getValueAt(row, 2).toString();
        String nama_peng = buku_table.getValueAt(row, 3).toString();
        String id_pen = buku_table.getValueAt(row, 4).toString();
        String nama_pen = buku_table.getValueAt(row, 5).toString();
        String price = buku_table.getValueAt(row, 6).toString();
        String hal = buku_table.getValueAt(row, 7).toString();
        String stock = buku_table.getValueAt(row, 8).toString();

        this.selectedBukuID = id;
        txt_nama.setText(nama);
        txt_pengarang.setText(id_peng);
        nama_pengarang.setText(nama_peng);
        txt_penerbit.setText(id_pen);
        nama_penerbit.setText(nama_pen);
        txt_harga.setText(price);
        txt_hal.setText(hal);
        txt_stock.setText(stock);
    }//GEN-LAST:event_buku_tableMouseClicked

    private void btnBook_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_resetMouseClicked
        this._resetField();
    }//GEN-LAST:event_btnBook_resetMouseClicked

    private void btnBook_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_deleteMouseClicked
        if(this.selectedBukuID != null) {
            int confirm = JOptionPane.showConfirmDialog(this, "Kamu yakin akan menghapus buku ini?", "Peringatan", JOptionPane.OK_CANCEL_OPTION);
            if(confirm == 0) {
                int row = buku_table.getSelectedRow();
                String id_buku = buku_table.getValueAt(row, 0).toString();

                try {
                    String query = "DELETE FROM buku WHERE id_buku = '" + id_buku + "'";
                    Connection conn = (Connection)Database.GetConnection();
                    PreparedStatement ps = conn.prepareStatement(query);
                    ps.execute();
                    ps.close();
                    conn.close();

                    this._resetField();
                    this._datatables();
                    JOptionPane.showMessageDialog(this, "Berhasil menghapus data");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data, data sedang terpakai");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
        }
    }//GEN-LAST:event_btnBook_deleteMouseClicked

    private void btnBook_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_submitMouseClicked
        if(!txt_nama.getText().equals("") && !txt_pengarang.getText().equals("") && !nama_pengarang.getText().equals("") && !txt_penerbit.getText().equals("") && !nama_penerbit.getText().equals("") && !txt_harga.getText().equals("") && !txt_hal.getText().equals("")) {
            if(this.selectedBukuID != null) {
                JOptionPane.showMessageDialog(this, "Data sudah ada didatabase!");
            } else {
                String nama = txt_nama.getText();
                String id_pengarang = txt_pengarang.getText();
                String id_penerbit = txt_penerbit.getText();
                String harga = txt_harga.getText();
                String halaman = txt_hal.getText();
                String stock = txt_stock.getText();

                try {
                    String query = "INSERT INTO buku (id_buku, id_penerbit, id_pengarang, nama, harga, jumlah_halaman, stock) VALUES (NULL, '" + id_penerbit + "', '" + id_pengarang + "', '" + nama + "', '" + harga + "', '" + halaman + "', '" + stock + "')";
                    Connection conn = (Connection)Database.GetConnection();
                    PreparedStatement ps = conn.prepareStatement(query);
                    ps.execute();
                    ps.close();
                    conn.close();

                    this._datatables();
                    this._resetField();
                    JOptionPane.showMessageDialog(this, "Berhasil menambahkan data");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menambahkan data");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
        }
    }//GEN-LAST:event_btnBook_submitMouseClicked

    private void btnBook_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_saveMouseClicked
        if(this.selectedBukuID == null) {
            JOptionPane.showMessageDialog(this, "Error! Silahkan pilih data yang akan diubah");
        } else {
            try {
                String nama = txt_nama.getText();
                String id_pengarang = txt_pengarang.getText();
                String id_penerbit = txt_penerbit.getText();
                String harga = txt_harga.getText();
                String halaman = txt_hal.getText();
                String stock = txt_stock.getText();
                
                String query = "UPDATE buku SET nama = '" + nama + "', id_penerbit = '" + id_penerbit + "', id_pengarang = '" + id_pengarang + "', harga = '" + harga + "', jumlah_halaman = '" + halaman + "', stock = '" + stock + "' WHERE id_buku = '" + this.selectedBukuID + "'";
                Connection conn = (Connection)Database.GetConnection();
                PreparedStatement ps = conn.prepareStatement(query);
                ps.execute();
                ps.close();
                conn.close();

                this._datatables();
                this._resetField();
                JOptionPane.showMessageDialog(this, "Berhasil mengubah data");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengubah data");
            }
        }
    }//GEN-LAST:event_btnBook_saveMouseClicked

    private void txt_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusGained
        if(txt_cari.getText().equals("Cari berdasarkan nama")) {
            txt_cari.setText("");
            txt_cari.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_cariFocusGained

    private void txt_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusLost
        if(txt_cari.getText().equals("")) {
            txt_cari.setText("Cari berdasarkan nama");
            txt_cari.setForeground(new Color(153, 153, 153));
        } else {
            txt_cari.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariFocusLost

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        try {
            String input = txt_cari.getText();
            String query = "SELECT * FROM buku JOIN penerbit ON buku.id_penerbit = penerbit.id_penerbit JOIN pengarang ON buku.id_pengarang = pengarang.id_pengarang WHERE CONCAT(id_buku, pengarang.id_pengarang, pengarang.nama, penerbit.id_penerbit, penerbit.nama, buku.nama, buku.harga, buku.jumlah_halaman) LIKE '%" + input + "%'";
            Connection conn = (Connection)Database.GetConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();

            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID");
            tbl.addColumn("Nama");
            tbl.addColumn("ID Pengarang");
            tbl.addColumn("Pengarang");
            tbl.addColumn("ID Penerbit");
            tbl.addColumn("Penerbit");
            tbl.addColumn("Harga");
            tbl.addColumn("Jumlah Hal");
            tbl.addColumn("Stock");
            buku_table.setModel(tbl);
            while(result.next()) {
                tbl.addRow(new Object[] {
                    result.getString("id_buku"),
                    result.getString("buku.nama"),
                    result.getString("pengarang.id_pengarang"),
                    result.getString("pengarang.nama"),
                    result.getString("penerbit.id_penerbit"),
                    result.getString("penerbit.nama"),
                    result.getString("buku.harga"),
                    result.getString("buku.jumlah_halaman"),
                    result.getString("buku.stock"),
                });
                buku_table.setModel(tbl);
            }
        } catch(Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil data");
        }
    }//GEN-LAST:event_txt_cariKeyReleased

    private void btnSearch_pengarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch_pengarangMouseClicked
        try {
            String query = "SELECT * FROM pengarang WHERE id_pengarang = '" + txt_pengarang.getText() + "'";
            Connection conn = (Connection)Database.GetConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            if(result.next()) {
                nama_pengarang.setText(result.getString("nama"));
            } else {
                nama_pengarang.setText("");
                JOptionPane.showMessageDialog(rootPane, "Maaf, pengarang tidak ditemukan silahkan periksa kembali!");
            }
            ps.close();
            conn.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSearch_pengarangMouseClicked

    private void btnSearch_penerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch_penerbitMouseClicked
        try {
            String query = "SELECT * FROM penerbit WHERE id_penerbit = '" + txt_penerbit.getText() + "'";
            Connection conn = (Connection)Database.GetConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            if(result.next()) {
                nama_penerbit.setText(result.getString("nama"));
            } else {
                nama_penerbit.setText("");
                JOptionPane.showMessageDialog(rootPane, "Maaf, penerbit tidak ditemukan silahkan periksa kembali!");
            }
            ps.close();
            conn.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSearch_penerbitMouseClicked

    protected void _resetField() {
        this.selectedBukuID = null;
        txt_nama.setText("");
        txt_pengarang.setText("");
        nama_pengarang.setText("");
        txt_penerbit.setText("");
        nama_penerbit.setText("");
        txt_harga.setText("");
        txt_hal.setText("");
        txt_stock.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Topbar;
    private javax.swing.JPanel ZeroLayout5;
    private javax.swing.JPanel btnBook_delete;
    private javax.swing.JPanel btnBook_reset;
    private javax.swing.JPanel btnBook_save;
    private javax.swing.JPanel btnBook_submit;
    private javax.swing.JPanel btnSearch_penerbit;
    private javax.swing.JPanel btnSearch_pengarang;
    private javax.swing.JPanel btn_back5;
    private javax.swing.JTable buku_table;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nama_penerbit;
    private javax.swing.JTextField nama_pengarang;
    private javax.swing.JLabel tanggal_hari_ini;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_hal;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
}
