package Main;


import Config.Database;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Main.Date.CurrentDate;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.UUID;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Illuminate
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Transaksi() {
        initComponents();
        setExtendedState(1280);
        _setDate();
    }
    
    private void _setDate() {
        CurrentDate cd = new CurrentDate();
        tanggal_hari_ini.setText(cd.getCurDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZeroLayout = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        side_logo = new javax.swing.JLabel();
        side_name = new javax.swing.JLabel();
        side_role = new javax.swing.JLabel();
        paneDashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paneTransaksi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paneMaster = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paneLogout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Topbar = new javax.swing.JPanel();
        tanggal_hari_ini = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama_anggota = new javax.swing.JTextField();
        text_anggota = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSearch_anggota = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomor_buku = new javax.swing.JTextField();
        btnSearch_book = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        nama_buku = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        due_date = new javax.swing.JComboBox<>();
        btnBook_reset = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnBook_delete = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnBook_submit = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cart_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaksi");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        ZeroLayout.setBackground(new java.awt.Color(255, 255, 255));
        ZeroLayout.setMaximumSize(new java.awt.Dimension(1920, 1080));
        ZeroLayout.setMinimumSize(new java.awt.Dimension(1280, 720));
        ZeroLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidebar.setBackground(new java.awt.Color(22, 30, 84));
        Sidebar.setMinimumSize(new java.awt.Dimension(0, 720));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo_x1.png"))); // NOI18N
        Sidebar.add(side_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 50, -1, -1));

        side_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        side_name.setForeground(new java.awt.Color(255, 255, 255));
        side_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        side_name.setText("Rihanna");
        Sidebar.add(side_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 261, 299, -1));

        side_role.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        side_role.setForeground(new java.awt.Color(255, 255, 255));
        side_role.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        side_role.setText("Administrator");
        Sidebar.add(side_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 287, 299, -1));

        paneDashboard.setBackground(new java.awt.Color(22, 30, 84));
        paneDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneDashboardMouseClicked(evt);
            }
        });
        paneDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dashboard_x1.png"))); // NOI18N
        paneDashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dashboard");
        paneDashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 20));

        Sidebar.add(paneDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 299, 39));

        paneTransaksi.setBackground(new java.awt.Color(20, 39, 155));
        paneTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/transaksi_x1.png"))); // NOI18N
        paneTransaksi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, 30, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transaksi");
        paneTransaksi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 20));

        Sidebar.add(paneTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 299, 39));

        paneMaster.setBackground(new java.awt.Color(22, 30, 84));
        paneMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneMasterMouseClicked(evt);
            }
        });
        paneMaster.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/master_x1.png"))); // NOI18N
        paneMaster.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Master");
        paneMaster.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 20));

        Sidebar.add(paneMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 299, 39));

        paneLogout.setBackground(new java.awt.Color(22, 30, 84));
        paneLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneLogoutMouseClicked(evt);
            }
        });
        paneLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout_x1.png"))); // NOI18N
        paneLogout.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, 30, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Log out");
        paneLogout.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 20));

        Sidebar.add(paneLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 299, 39));

        ZeroLayout.add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 299, 720));

        Topbar.setBackground(new java.awt.Color(20, 39, 155));
        Topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanggal_hari_ini.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggal_hari_ini.setForeground(new java.awt.Color(255, 255, 255));
        tanggal_hari_ini.setText("24 Desember 2077");
        Topbar.add(tanggal_hari_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 26, -1, -1));

        ZeroLayout.add(Topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 990, 66));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nama Anggota");
        ZeroLayout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        nama_anggota.setEnabled(false);
        ZeroLayout.add(nama_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 245, 29));
        ZeroLayout.add(text_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 181, 29));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("ID Anggota");
        ZeroLayout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 30));

        btnSearch_anggota.setBackground(new java.awt.Color(22, 30, 84));
        btnSearch_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch_anggotaMouseClicked(evt);
            }
        });
        btnSearch_anggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cari");
        btnSearch_anggota.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        ZeroLayout.add(btnSearch_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 60, 29));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nomor Buku");
        ZeroLayout.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, 30));
        ZeroLayout.add(nomor_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 181, 29));

        btnSearch_book.setBackground(new java.awt.Color(22, 30, 84));
        btnSearch_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch_bookMouseClicked(evt);
            }
        });
        btnSearch_book.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cari");
        btnSearch_book.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        ZeroLayout.add(btnSearch_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 70, 29));

        nama_buku.setEnabled(false);
        ZeroLayout.add(nama_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 260, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Nama Buku");
        ZeroLayout.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 90, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Lama peminjaman (hari)");
        ZeroLayout.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 180, 30));

        due_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "7", "14", "30" }));
        ZeroLayout.add(due_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 260, 30));

        btnBook_reset.setBackground(new java.awt.Color(22, 30, 84));
        btnBook_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_resetMouseClicked(evt);
            }
        });
        btnBook_reset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Reset");
        btnBook_reset.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        ZeroLayout.add(btnBook_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 70, 30));

        btnBook_delete.setBackground(new java.awt.Color(22, 30, 84));
        btnBook_delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Hapus");
        btnBook_delete.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        ZeroLayout.add(btnBook_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 80, 30));

        btnBook_submit.setBackground(new java.awt.Color(22, 30, 84));
        btnBook_submit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Simpan");
        btnBook_submit.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        ZeroLayout.add(btnBook_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 70, 30));

        cart_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cart_table);

        ZeroLayout.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 600, 320));

        getContentPane().add(ZeroLayout, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paneDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneDashboardMouseClicked
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_paneDashboardMouseClicked

    private void paneMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneMasterMouseClicked
        new Master().setVisible(true);
        dispose();
    }//GEN-LAST:event_paneMasterMouseClicked

    private void paneLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneLogoutMouseClicked
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_paneLogoutMouseClicked

    private void btnSearch_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch_anggotaMouseClicked
        try {
            String query = "SELECT * FROM anggota WHERE id_anggota = '" + text_anggota.getText() + "'";
            Connection conn = (Connection)Database.GetConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            if(result.next()) {
                nama_anggota.setText(result.getString("nama"));
            } else {
                nama_anggota.setText("");
                JOptionPane.showMessageDialog(rootPane, "Maaf, anggota tidak ditemukan silahkan periksa kembali!");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSearch_anggotaMouseClicked

    private void btnSearch_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch_bookMouseClicked
        try {
            String query = "SELECT * FROM buku JOIN pengarang ON buku.id_pengarang = pengarang.id_pengarang WHERE id_buku = '" + nomor_buku.getText() + "'";
            Connection conn = (Connection)Database.GetConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            if(result.next()) {
                nama_buku.setText(result.getString("buku.nama") + " - " + result.getString("pengarang.nama"));
            } else {
                nama_buku.setText("");
                JOptionPane.showMessageDialog(rootPane, "Maaf, buku tidak ditemukan silahkan periksa kembali!");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSearch_bookMouseClicked

    private void btnBook_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_resetMouseClicked
        this.resetBook();
    }//GEN-LAST:event_btnBook_resetMouseClicked

    protected void resetTotal() {
        
    }
    
    protected void resetBook() {
        nomor_buku.setText("");
        nama_buku.setText("");
        due_date.setSelectedIndex(0);
    }
    
    protected void resetAnggota() {
        text_anggota.setText("");
        nama_anggota.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel Topbar;
    private javax.swing.JPanel ZeroLayout;
    private javax.swing.JPanel btnBook_delete;
    private javax.swing.JPanel btnBook_reset;
    private javax.swing.JPanel btnBook_submit;
    private javax.swing.JPanel btnSearch_anggota;
    private javax.swing.JPanel btnSearch_book;
    private javax.swing.JTable cart_table;
    private javax.swing.JComboBox<String> due_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama_anggota;
    private javax.swing.JTextField nama_buku;
    private javax.swing.JTextField nomor_buku;
    private javax.swing.JPanel paneDashboard;
    private javax.swing.JPanel paneLogout;
    private javax.swing.JPanel paneMaster;
    private javax.swing.JPanel paneTransaksi;
    private javax.swing.JLabel side_logo;
    private javax.swing.JLabel side_name;
    private javax.swing.JLabel side_role;
    private javax.swing.JLabel tanggal_hari_ini;
    private javax.swing.JTextField text_anggota;
    // End of variables declaration//GEN-END:variables
}
